name: .NET

on:
  push:
    branches: [ master ]
jobs:
  downloadcrowdintranslations:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'do not download translations')"
    steps:
    - uses: actions/checkout@v2
    - name: Download translations
      uses: crowdin/github-action@1.1.0
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true
        skip_untranslated_strings: true
        skip_untranslated_files: true
        push_translations: true
        commit_message: 'New Crowdin translations by Github Action'
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'New Crowdin pull request with translations'
        pull_request_labels: 'enhancement, good first issue'
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        translation: '/SilverBotDS/Languages'